import {
    Button,
    ComboBox,
    VerticalBox,
    HorizontalBox,
    Switch,
} from "std-widgets.slint";
import { ControlBar } from "control.slint";
import { PauseIcon } from "icons.slint";

import { CameraInfo, StatusState, CameraManager } from "globals.slint";
import { CameraView } from "camera_view.slint";

export { CameraInfo, StatusState, CameraManager }

export component App inherits Window {
    title: "Camera";
    preferred-width: 800px;
    preferred-height: 800px;

    background: #121212;

    callback refresh-cameras <=> control.refresh-cameras;
    callback start-camera <=> control.start-camera;
    callback stop-camera <=> control.stop-camera;

    // Properties from Rust
    in property <string> status-text: "Ready";
    in property <StatusState> status-state: StatusState.normal;

    VerticalBox {
        spacing: 10px;
        padding: 10px;

        control := ControlBar {
            z: 1;
        }

        CameraView { }

        // Status bar
        Rectangle {
            height: 30px;
            background: #222;
            border-radius: 3px;

            HorizontalLayout {
                padding: 5px;

                Text {
                    text: status-text;
                    color: {
                        if status-state == StatusState.normal {
                            #999
                        } else if status-state == StatusState.error {
                            #f00
                        } else if status-state == StatusState.success {
                            #0f0
                        } else {
                            #999
                        }
                    };
                    font-size: 12px;
                    vertical-alignment: center;
                }
            }
        }
    }
}
