import { CameraManager } from "globals.slint";
export component CameraView inherits Rectangle {
    background: #333333;
    border-width: 2px;
    border-color: #666;
    min-height: 400px;

    if (CameraManager.is-camera-active): Image {
        source: CameraManager.camera-frame;
        image-fit: contain;
        width: 100%;
        height: 100%;
    }

    if (!CameraManager.is-camera-active): Text {
        text: "No Camera Active\n\nSelect a camera and click 'Start' to begin";
        color: #999;
        font-size: 18px;
        horizontal-alignment: center;
        vertical-alignment: center;
        width: 100%;
        height: 100%;
    }

    if (CameraManager.is-streaming): Text {
        x: 1rem;
        y: parent.height - self.height - 1rem;
        text: "\{CameraManager.camera-frame.width}x\{CameraManager.camera-frame.height}";
        color: #FFF9;
        font-size: 11px;
    }

    if (CameraManager.is-streaming): Text {
        x: parent.width - self.width - 1rem;
        y: parent.height - self.height - 1rem;
        text: "\{CameraManager.fps} FPS";
        color: #FFF9;
        font-size: 11px;
    }
}
