import { CameraInfo } from "globals.slint";
import { Button } from "std-widgets.slint";

export component CamerasComboBox {
    in property <[CameraInfo]> cameras;
    in property <bool> enabled: true;
    in-out property <CameraInfo> selected;

    out property <bool> is-opened;

    Rectangle {
        width: list.width;
        height: selected-text.height + 15px;

        background: ta.has-hover ? #F00.darker(20%) : #F00;

        border-radius: 5px;

        selected-text := Text {
            text: selected.name.character-count != 0 ? selected.name : "Select camera";
            font-size: 16px;
        }

        ta := TouchArea {
            mouse-cursor: pointer;
            clicked => {
                is-opened = !is-opened;
            }
        }
    }

    Rectangle {
        height: !is-opened ? 0 : cameras.length * (10px + 14px * 1.2) + 4px + 5px;
        y: selected-text.height + (is-opened ? 20px : 10px);
        transform-scale: is-opened ? 1 : 0.90;
        clip: true;

        background: #333;
        border-radius: 5px;
        border-width: 2px;
        border-color: #666;

        animate height, y, transform-scale { duration: 100ms; }

        list := VerticalLayout {
            y: 5px;
            alignment: stretch;
            padding-left: 10px;
            padding-right: 10px;

            for camera in cameras: Rectangle {
                width: list.width - 15px;
                height: cam.height + 10px;

                ta-item := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        selected = camera;
                        is-opened = false;
                    }
                }

                Rectangle {
                    x: -2.5px;
                    width: 10px;
                    height: 10px;
                    background: #666;
                    border-radius: 50px;

                    Rectangle {
                        width: 8px;
                        height: 8px;
                        background: #333;
                        border-radius: 50px;
                    }

                    Rectangle {
                        visible: selected == camera || ta-item.has-hover;
                        width: 5px;
                        height: 5px;
                        background: selected != camera && ta-item.has-hover ? #666 : #F00;
                        border-radius: 50px;
                    }
                }

                cam := Text {
                    x: 12px;
                    text: camera.name;
                    font-size: 14px;
                }
            }
        }
    }

    // allocate required sized
    VerticalLayout {
        visible: false;
        for camera in cameras: Text {
            text: camera.name;
            font-size: 16px;
        }
    }
}
