import { Button } from "std-widgets.slint";
import { CamerasComboBox } from "combobox.slint";
import { CameraInfo, CameraManager } from "globals.slint";
import { PauseIcon, RefreshIcon } from "icons.slint";

export component ControlBar inherits Rectangle {
    height: 50px;

    callback refresh-cameras();
    callback stop-camera();
    callback start-camera();

    // When camera is starting up, it takes a lot of cpu time that prevents 
    // pause icon beign updated correctly, so should delayed UI to a good
    // looking animations, this needs to have a way to tell pause icon that
    // the thread is not busy anymore
    public function refresh-pause-icon() {
        paused.is-play = !CameraManager.is-camera-active;
    }

    init => {
        paused.is-play = !CameraManager.is-camera-active;
    }

    Rectangle {
        background: rgba(0, 0, 0, 0.8);
        border-radius: 4px;
        border-width: 1px;
        border-color: #333;

        Rectangle {
            x: parent.width - 50px;
            width: 30px;
            height: 30px;

            paused := PauseIcon {
                width: parent.width;
                height: parent.height;
            }

            TouchArea {
                clicked => {
                    if CameraManager.is-camera-active {
                        stop-camera();
                    } else {
                        start-camera();
                    }
                }
            }
        }

        HorizontalLayout {
            x: 0;
            width: parent.width - 70px;
            padding: 10px;
            spacing: 10px;

            TouchArea {
                width: 30px;
                height: 30px;
                enabled: !CameraManager.is-camera-active;

                Rectangle {
                    border-radius: 50px;
                    background: parent.has-hover ? #FFF3 : transparent;
                }

                RefreshIcon {
                    width: 24px;
                    stroke: CameraManager.is-camera-active ? #FFF9 : white;
                }

                clicked => {
                    refresh-cameras();
                }
            }

            if (CameraManager.cameras.length != 0): CamerasComboBox {
                cameras: CameraManager.cameras;
                enabled: !CameraManager.is-camera-active;
                selected <=> CameraManager.selected-camera;
                width: 250px;
            }

            if (CameraManager.cameras.length == 0): Text {
                text: "No cameras found";
                vertical-alignment: center;
                font-size: 17px;
            }
        }
    }
}
